# Generated by Django 4.2.1 on 2023-09-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rain_measurement_system_app", "0001_initial"),
    ]

    operations = []
