# Generated by Django 4.2.1 on 2023-09-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rain_measurement_system_app", "0003_initial"),
    ]

    operations = []
