# Generated by Django 4.2.1 on 2023-09-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rain_measurement_system_app", "0004_auto_20230922_2136"),
    ]

    operations = []
