# Generated by Django 4.2.6 on 2023-10-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rain_measurement_system_app", "0005_auto_20230922_2138"),
    ]

    operations = []
