# Generated by Django 4.2.6 on 2023-10-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rain_measurement_system_app", "0008_auto_20231023_0123"),
    ]

    operations = []
