# Generated by Django 5.0.3 on 2024-03-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rain_measurement_system_app', '0009_auto_20231023_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Device_mac_address', models.CharField(max_length=17)),
                ('Network_ssid', models.CharField(max_length=30)),
                ('Network_ip', models.CharField(max_length=30)),
                ('Database_name', models.CharField(max_length=50)),
                ('Database_ip', models.CharField(max_length=30)),
                ('Database_port', models.IntegerField()),
                ('Database_user_name', models.CharField(max_length=50)),
                ('Data_aktualizacji', models.DateField()),
                ('Czas_aktualizacji', models.TimeField()),
            ],
            options={
                'db_table': 'device_info',
            },
        ),
        migrations.AlterModelOptions(
            name='logs',
            options={},
        ),
        migrations.AlterModelOptions(
            name='raingaugae',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rainsensor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='watersensor',
            options={},
        ),
    ]
