# Generated by Django 5.0.3 on 2024-03-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rain_measurement_system_app', '0010_deviceinfo_alter_logs_options_and_more'),
    ]

    operations = [
    ]
